### ISSUE TITLE
No such file or dir

### ISSUE THREAD

**Issue by bluethumb** [DANOSOFT/saldi#14]
En af de små ting :+1: 
kreditor/kreditorkort.php:
443 print "<script language=\"javascript\" type=\"text/javascript\" src=\"../javascript/cvrapi.js\"></script>\n";

Filen er ikke tilstede og giver er "error"
failed (2: No such file or directory) 

Den linje kan vel slettes  !?

**Comment by logicguy1** [comment]
Hej Bluethumb,

Tak for dit issue, cvrapi.js står for at hente CVR data ned og ligge det ind i input felterne på kontokortet. Funktionen der bliver lavet i filen er rykket ind i https://github.com/DANOSOFT/saldi/blob/master/javascript/cvrapiopslag.js#L33-L59 og skal eneligt bare have omdøbt det script den trækker ind.

**Comment by logicguy1** [comment]
Fixed in 8bfab276100642d63e68dd349c00ca21e2e25bb7
