### ISSUE TITLE
debitor/ordre.php - lineCost

### ISSUE THREAD

**Issue by rgry** [DANOSOFT/saldi#21]
Tænker at $lineCost[$x]=0 burde være sat inden at den anvendes til += - giver php warning
onkring linje 2690

		while ($row = db_fetch_array($query))	{
			if (($row['posnr']>0)) {
				$x++;

				$lineCost[$x]=0; #RG 20241216

				$linje_id[$x]=$row['id'];

**Comment by rgry** [comment]
https://github.com/DANOSOFT/saldi/blob/master/debitor/ordre.php

**Comment by logicguy1** [comment]
Fixed in: ecb7fafcabe3137769c4a09816128bb9c4a98bc0
